name: Debian package builder
description: Build a debian package 
branding:
  color: green
  icon: package
inputs:
  docker_image:
    description: "name of the docker image used to build the package"
    required: false
    default: 'debian:stable'
  source_directory:
    description: "path to the directory where the source of the package is located"
    required: false
    default: './'
  build_directory:
    description: "path to the directory where the build artifacts will be placed"
    required: false
    default: '/artifacts'
  target_architecture:
    description: "package target architecture"
    required: false
    default: 'amd64'
  additional_env:
    description: "Additional environment variables for the build"
    required: false
    default: ''
  # Stages
  debug:
    description: "Display debug information while building"
    required: false
    default: '0'
  install_deps:
    description: "Install dependencies"
    required: false
    default: '1'
  install_build_deps:
    description: "Install package build dependencies"
    required: false
    default: '1'
  build:
    description: "If 'true', builds the package"
    required: false
    default: '1'
  check:
    description: "If 'true', checks the built package with lintian"
    required: false
    default: '1'
  # Build configuration
  signing_key:
    description: "Armored GPG key to use to sign packages"
    required: false
    default: ''
  signing_passphrase:
    description: "GPG passphrase to use to sign packages"
    required: false
    default: ''
  dpkg_buildpackage_include_debug_package:
    description: ""
    required: false
    default: '0'
  dpkg_buildpackage_harden_all:
    description: ""
    required: false
    default: '1'
  dpkg_buildpackage_force_include_source:
    description: ""
    required: false
    default: '1'
  dpkg_buildpackage_check_builddeps:
    description: ""
    required: false
    default: '0'
  dpkg_buildpackage_post_clean:
    description: ""
    required: false
    default: '0'
  # Quality check configuration - comma-separated lists
  lintian_dont_check_parts:
    description: ""
    required: false
    default: 'nmu'
  lintian_tags_to_suppress:
    description: ""
    required: false
    default: 'initial-upload-closes-no-bugs,debian-watch-file-is-missing'
  lintian_check_changelog_spelling:
    description: "Suppress 'spelling-error-in-changelog' tag if true"
    required: false
    default: true
  lintian_check_itp_bug:
    description: "Suppress 'initial-upload-closes-no-bugs' tag if false"
    required: false
    default: false
  lintian_check_watch_file:
    description: "Suppress 'debian-watch-file-is-missing' tag if false"
    required: false
    default: false
  # Quality check configuration - boolean
  lintian_display_info:
    description: ""
    required: false
    default: '1'
  lintian_show_overrides:
    description: ""
    required: false
    default: '1'
  lintian_tag_display_limit:
    description: ""
    required: false
    default: '0'
  # LINTIAN_NO_FAIL overrides all others
  lintian_fail_on_error:
    description: ""
    required: false
    default: '1'
  lintian_fail_on_warning:
    description: ""
    required: false
    default: '1'
  lintian_fail_on_info:
    description: ""
    required: false
    default: '0'
  lintian_fail_on_pedantic:
    description: ""
    required: false
    default: '0'
  lintian_fail_on_experimental:
    description: ""
    required: false
    default: '0'
  lintian_fail_on_override:
    description: ""
    required: false
    default: '0'
  lintian_no_fail:
    description: ""
    required: false
    default: '0'
  # Additional options
  dpkg_buildpackage_opts:
    description: ""
    required: false
    default: ''
  lintian_opts:
    description: ""
    required: false
    default: ''

runs:
  using: node12
  main: main.js
  post: post.js
