name: pi-topOS Docker Base Image Build

on:
  push:
    paths:
      - "docker_base/**"
      - ".github/workflows/docker-build.yml"

env:
  BASE_IMAGE_FOR_LATEST: "buster-backports"
  IMAGE_NAME: "pitop/pi-top-os-deb-build"
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"

jobs:
  build-push-docker-hub:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        base_image: ['buster-backports', 'bullseye']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ matrix.base_image == env.BASE_IMAGE_FOR_LATEST }}
            prefix=${{ matrix.base_image }}-,onlatest=false
          tags: |
            type=ref,event=branch

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: docker_base
          build-args: DEBIAN_BASE_IMAGE=${{ matrix.base_image }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show image digest
        if: github.ref == 'refs/heads/master'
        run: echo ${{ steps.docker_build_push.outputs.digest }}
